# Generated by Django 2.2.3 on 2020-05-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=50)),
                ('voter_id', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('constituency', models.CharField(max_length=50)),
                ('has_voted', models.CharField(max_length=3)),
                ('where_voted', models.CharField(max_length=7, null=True)),
                ('ipaddress', models.GenericIPAddressField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
