# Generated by Django 2.2.3 on 2020-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '1VVoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterid_no', models.CharField(max_length=10)),
                ('complain', models.CharField(max_length=5000)),
                ('complain_reply', models.CharField(max_length=5000, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
    ]
