from django.urls import path
from . import views

urlpatterns = [
    path('adminhome', views.adminhome, name='adminhome'),
    path('adminprofile', views.adminprofile, name='adminprofile'),
    path('addvoter', views.addvoter, name='addvoter'),
    path('add_voter', views.add_voter, name='add_voter'),
    path('addcandidate', views.addcandidate, name='addcandidate'),
    path('add_candidate', views.add_candidate, name='add_candidate'),
    path('generateelection', views.generateelection, name='generateelection'),
    path('generate_election', views.generate_election, name='generate_election'),
    path('voting', views.voting, name='voting'),
    path('votervotesub', views.votervotesub, name='votervotesub'),
    path('completeelection', views.completeelection, name='completeelection'),
    path('complete_election', views.complete_election, name='complete_election'),
    path('modifyelection', views.modifyelection, name='modifyelection'),
    path('modify_election', views.modify_election, name='modify_election'),
    path('generateresult', views.generateresult, name='generateresult'),
    path('viewcandidatesforaddvote', views.viewcandidatesforaddvote, name='viewcandidatesforaddvote'),
    path('submitevmvote', views.submitevmvote, name='submitevmvote'),
    path('generatereport', views.generatereport, name='generatereport'),
    path('generate_report', views.generate_report, name='generate_report'),
    path('viewcandidate', views.viewcandidate, name='viewcandidate'),
    path('view_candidate', views.view_candidate, name='view_candidate'),
    path('viewvoter', views.viewvoter, name='viewvoter'),
    path('view_voter', views.view_voter, name='view_voter'),
    path('editvoter', views.editvoter, name='editvoter'),
    path('edit_voter', views.edit_voter, name='edit_voter'),
    path('editvoterdetails', views.editvoterdetails, name='editvoterdetails'),
    path('editcandidate', views.editcandidate, name='editcandidate'),
    path('edit_candidate', views.edit_candidate, name='edit_candidate'),
    path('editcandidatedetails', views.editcandidatedetails, name='editcandidatedetails'),
    path('viewresult', views.viewresult, name='viewresult'),
    path('view_result', views.view_result, name='view_result'),
    path('view_result_filter', views.view_result_filter, name='view_result_filter'),
    path('viewreport', views.viewreport, name='viewreport'),
    path('view_report', views.view_report, name='view_report'),
    path('viewcomplain', views.viewcomplain, name='viewcomplain'),
    path('replycomplain', views.replycomplain, name='replycomplain'),
    path('reply_complain', views.reply_complain, name='reply_complain'),
    path('achangepassword', views.achangepassword, name='achangepassword'),
    path('achange_password', views.achange_password, name='achange_password'),
]