# Generated by Django 2.2.3 on 2020-05-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '6Reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='affidavit',
            field=models.FileField(null=True, upload_to='CandidateAffidavit/'),
        ),
    ]
