# Generated by Django 2.2.3 on 2020-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '1V'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=1024)),
                ('mobile_no', models.BigIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('constituency', models.CharField(max_length=50)),
                ('parliamentary', models.CharField(blank=True, max_length=50, null=True)),
                ('assembly', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate_image', models.ImageField(upload_to='CandidateImage/')),
                ('candidate_party', models.CharField(max_length=50)),
                ('party_image', models.ImageField(upload_to='PartyImage/')),
            ],
        ),
    ]
