# Generated by Django 2.2.3 on 2020-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '3Election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('election_id', models.CharField(max_length=50)),
                ('candidate_id', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_party', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('constituency', models.CharField(max_length=50)),
                ('online_votes', models.BigIntegerField(default=0)),
                ('evm_votes', models.BigIntegerField(default=0)),
                ('total_votes', models.BigIntegerField(default=0)),
            ],
        ),
    ]
