# Generated by Django 2.2.3 on 2020-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '4Total_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC_Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('ecadmin_id', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=1024)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ecadmin_image', models.ImageField(upload_to='ECAdminImage/')),
            ],
        ),
    ]
