# Generated by Django 2.2.3 on 2020-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '5EC_Admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('constituency', models.CharField(max_length=50)),
                ('electors_male', models.BigIntegerField(default=0)),
                ('electors_female', models.BigIntegerField(default=0)),
                ('electors_others', models.BigIntegerField(default=0)),
                ('electors_total', models.BigIntegerField(default=0)),
                ('voters_male', models.BigIntegerField(default=0)),
                ('voters_female', models.BigIntegerField(default=0)),
                ('voters_others', models.BigIntegerField(default=0)),
                ('voters_total', models.BigIntegerField(default=0)),
                ('poll_male', models.FloatField()),
                ('poll_female', models.FloatField()),
                ('poll_others', models.FloatField()),
                ('poll_total', models.FloatField()),
            ],
        ),
    ]
